### PR TITLE
Automatic data removal

### PR DESCRIPTION
**Pull request by BMehlkop**
I've added all information I have about the automatic data removal topic and had a go at finding a proper structure for the various documents. I find myself a bit limited by not being able to have a multi-layer menu structure though.

Suggestions and comments very welcome!

### CODE REVIEW

**Comment by relitodea** [comment]
Is the clean duration 31 or 56 now?

**Comment by BMehlkop** [comment]
Hi Reli,

as the documentation says, it's 56 now.

**Comment by relitodea** [comment]
in the document is still "after 31 days"

**Comment by relitodea** [comment]
can we link these items somehow in the main Index? FAQ/UserGuide

**Comment by BMehlkop** [comment]
Hi Reli, the latest version says 56 days for me. All these items are also included in the menu.

Are you looking at the latest version?

**Comment by relitodea** [comment]
I am looking in the PR code

**Comment by BMehlkop** [comment]
Perhaps we can share screens? I suspect you're looking at a specific commit.

**Pull request merged**
